baseurl: "/jekyll-tryouts"
title: "Jekyll Tryouts" # used to set site title / name

collections:
  authors:
    output: true
  technologies:
    output: true
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "technologies"
    values:
      layout: "technology"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
